from enum import Enum, auto


class TextType(Enum):
    Car_Create_Menu = auto()
    Car_Create_Category = auto()
    Car_Create_Licence_Plate = auto()
    Car_Create_Type = auto()
    Car_Create_Currency = auto()
    Car_Create_Amount = auto()
    Rental_Create_Menu = auto()
    Rental_Create_Name = auto()
    Rental_Create_Another_Car = auto()
    Rental_Create_Select_car = auto()
    Rental_Create_New_Existing_Car = auto()
    Rental_Create_Add_Car_Menu = auto()
    Rental_Delete_Menu = auto()
    Rental_Delete_Id = auto()
    Rental_List_Menu = auto()
    Rental_List_Back = auto()
    Rental_Update_Menu = auto()
    Rental_Update_Id = auto()
    Rental_Update_Add_Another = auto()
    Rental_Update_Remove_Another = auto()
    Rental_Update_Select_Car = auto()
    Rental_Update_New_Existing_Car = auto()
    Rental_Update_Add_Car_Menu = auto()
    Rental_Update_Add_Remove_Car = auto()
    Rental_Update_Add_Menu = auto()
    Rental_Update_Remove_Menu = auto()
    Rent_Create_Menu = auto()
    Rent_Create_Rental = auto()
    Rent_Create_Car = auto()
    Rent_Create_Date = auto()
    Rent_Error_Reserved = auto()
    Rent_Delete_Menu = auto()
    Rent_Delete_Id = auto()
    Exit_Menu = auto()
    Exit_Sure_Exit = auto()
    Back_Menu = auto()
    Rent_List_Menu = auto()
    Rent_List_Back = auto()
    Main_Menu = auto()
    Manage_Rent_Menu = auto()
    Manage_Rental_Menu = auto()
    Choose_Language_Menu = auto()
    Language_Select = auto()
